sudo: false
language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
   # disable xdebug if not coverage
  - if [[ $COVERAGE == "" ]]; then phpenv config-rm xdebug.ini; fi

script:
  - vendor/bin/phpunit --bootstrap vendor/autoload.php tests

after_script:
    - |
      if [[ $COVERAGE == true && $TRAVIS_BRANCH == "master" ]]; then
        vendor/bin/phpunit --coverage-clover coverage.xml
        wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
        php php-coveralls.phar --verbose
      fi