sudo: false
language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

cache:
  directories:
    - $HOME/.composer/cache/files

# Commands to be run before your environment runs.
before_script:
  - composer self-update
   # disable xdebug if not coverage
  - if [[ $CODE_COVERAGE == "" ]]; then phpenv config-rm xdebug.ini; fi
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpunit --bootstrap vendor/autoload.php tests

jobs:
  allow_failures:
    - php: nightly

  include:
    - stage: Quality assurance
      env: 
        - CODE_COVERAGE=yes
      # before_script:
      #   - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
      #   - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script: vendor/bin/phpunit --bootstrap vendor/autoload.php --whitelist Formularium --coverage-clover ./clover.xml tests/
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover ./clover.xml

    - stage: Quality assurance
      env: STATIC_ANALYSIS
      install: travis_retry composer install
      script: vendor/bin/phpstan analyze Formularium

    - stage: Publish kitchen sink
      env: KITCHEN_SINK
      before_deploy:
        - php util/makeKitchenSink.php
        - composer coverage
        - composer apidoc
      script: skip
      deploy:
        provider: pages:git
        token: ${GITHUB_TOKEN}
        cleanup: true
        edge: true
        local_dir: docs/
