<?php declare(strict_types=1);

namespace Formularium\Datatype;

use Formularium\Field;
use Formularium\Exception\ValidatorException;

class Datatype_language extends \Formularium\Datatype\Datatype_choice
{
    public function __construct(string $typename = 'language', string $basetype = 'choice')
    {
        parent::__construct($typename, $basetype);
        $this->choices = [
            'aa' => 'Afaraf',
            'ab' => 'Аҧсуа',
            'ae' => 'avesta',
            'af' => 'Afrikaans',
            'ak' => 'Akan',
            'am' => 'አማርኛ',
            'an' => 'Aragonés',
            'ang' => 'Anglo-Saxon (Englisc)',
            'ar' => 'العربية',
            'arc' => 'ܐܪܡܝܐ',
            'as' => 'অসমীয়া',
            'ast' => 'Asturianu',
            'av' => 'авар мацӀ; магӀарул мацӀ',
            'ay' => 'Aymar aru',
            'az' => 'azərbaycan dili',
            'ba' => 'башҡорт теле',
            'bar' => 'Boarisch',
            'bat-smg' => 'Žemaitėška',
            'bcl' => 'Bikol',
            'be' => 'Беларуская',
            'be-tarask' => 'Беларуская (тарашкевіца)',
            'bg' => 'български език',
            'bh' => 'भोजपुरी',
            'bi' => 'Bislama',
            'bm' => 'bamanankan',
            'bn' => 'বাংলা',
            'bo' => 'བོད་ཡིག',
            'bpy' => 'ইমার ঠার/বিষ্ণুপ্রিয়া মণিপুরী ',
            'br' => 'brezhoneg',
            'bs' => 'bosanski jezik',
            'ca' => 'Català',
            'ce' => 'нохчийн мотт',
            'ceb' => 'Sinugboanong Binisaya',
            'ch' => 'Chamoru',
            'co' => 'Corsu; Lingua corsa',
            'cr' => 'ᓀᐦᐃᔭᐍᐏᐣ',
            'cs' => 'česky; čeština',
            'cu' => 'ѩзыкъ словѣньскъ',
            'cv' => 'чӑваш чӗлхи',
            'cy' => 'Cymraeg',
            'da' => 'dansk',
            'de' => 'Deutsch',
            'dz' => 'རྫོང་ཁ',
            'ee' => 'Ɛʋɛgbɛ',
            'el' => 'Ελληνικά',
            'en' => 'English',
            'eo' => 'Esperanto',
            'es' => 'Español; castellano',
            'et' => 'Eesti keel',
            'eu' => 'euskara',
            'fa' => 'فارسی',
            'ff' => 'Fulfulde',
            'fi' => 'suomen kieli',
            'fj' => 'vosa Vakaviti',
            'fo' => 'Føroyskt',
            'fr' => 'Français',
            'fy' => 'Frysk',
            'ga' => 'Gaeilge',
            'gd' => 'Gàidhlig',
            'gl' => 'Galego',
            'gn' => 'Avañe\'ẽ',
            'gsw' => 'Allemanisch',
            'gu' => 'ગુજરાતી',
            'gv' => 'Gaelg; Gailck',
            'ha' => 'هَوُسَ',
            'he' => 'עברית',
            'hi' => 'हिन्दी; हिंदी',
            'ho' => 'Hiri Motu',
            'hr' => 'Hrvatski',
            'ht' => 'Kreyòl ayisyen',
            'hu' => 'Magyar',
            'hy' => 'Հայերեն',
            'hz' => 'Otjiherero',
            'ia' => 'Interlingua',
            'id' => 'Bahasa Indonesia',
            'ie' => 'Interlingue',
            'ig' => 'Igbo',
            'ii' => 'ꆇꉙ',
            'ik' => 'Iñupiaq; Iñupiatun',
            'io' => 'Ido',
            'is' => 'Íslenska',
            'it' => 'Italiano',
            'iu' => 'ᐃᓄᒃᑎᑐᑦ',
            'ja' => '日本語 (にほんご／にっぽんご)',
            'jv' => 'basa Jawa',
            'ka' => 'ქართული',
            'kg' => 'KiKongo',
            'ki' => 'Gĩkũyũ',
            'kj' => 'Kuanyama',
            'kk' => 'Қазақ тілі',
            'kl' => 'kalaallisut; kalaallit oqaasii',
            'km' => 'ភាសាខ្មែរ',
            'kn' => 'ಕನ್ನಡ',
            'ko' => '한국어 (韓國語); 조선말 (朝鮮語)',
            'kr' => 'Kanuri',
            'ks' => 'कश्मीरी; كشميري‎',
            'ku' => 'Kurdî; كوردی‎',
            'kv' => 'коми кыв',
            'kw' => 'Kernewek',
            'ky' => 'кыргыз тили',
            'la' => 'latine; lingua latina',
            'lb' => 'Lëtzebuergesch',
            'lg' => 'Luganda',
            'li' => 'Limburgs',
            'ln' => 'Lingála',
            'lo' => 'ພາສາລາວ',
            'lt' => 'lietuvių kalba',
            'lu' => 'Luba-Katanga',
            'lv' => 'latviešu valoda',
            'mg' => 'Malagasy fiteny',
            'mh' => 'Kajin M̧ajeļ',
            'mi' => 'te reo Māori',
            'mk' => 'македонски јазик',
            'ml' => 'മലയാളം',
            'mn' => 'Монгол',
            'mr' => 'मराठी',
            'ms' => 'bahasa Melayu; بهاس ملايو‎',
            'mt' => 'Malti',
            'my' => 'ဗမာစာ',
            'na' => 'Ekakairũ Naoero',
            'nah' => 'Nāhuatl',
            'nap' => 'Nnapulitano',
            'nb' => 'Norsk bokmål',
            'nds' => 'Plattdüütsch',
            'nds-nl' => 'Nedersaksisch',
            'new' => 'नेपाली',
            'ng' => 'Owambo',
            'nl' => 'Nederlands',
            'nn' => 'Norsk nynorsk',
            'no' => 'Norsk',
            'nv' => 'Diné bizaad; Dinékʼehǰí',
            'ny' => 'chiCheŵa; chinyanja',
            'oc' => 'Occitan',
            'oj' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
            'om' => 'Afaan Oromoo',
            'or' => 'ଓଡ଼ିଆ',
            'os' => 'Ирон æвзаг',
            'pa' => 'ਪੰਜਾਬੀ; پنجابی‎',
            'pi' => 'पाऴि',
            'pl' => 'Polski',
            'pms' => 'Piemontèis',
            'ps' => 'پښتو',
            'pt' => 'Português',
            'pt-br' => 'Português (Brasil)',
            'qu' => 'Runa Simi; Kichwa',
            'rm' => 'rumantsch grischun',
            'rn' => 'kiRundi',
            'ro' => 'Română',
            'ru' => 'русский язык',
            'rw' => 'Ikinyarwanda',
            'sa' => 'संस्कृतम्',
            'sc' => 'Sardu',
            'scn' => 'Sicilianu',
            'sd' => 'सिन्धी; سنڌي، سندھی‎',
            'se' => 'Davvisámegiella',
            'sg' => 'yângâ tî sängö',
            'sh' => 'Srpskohrvatski; Српскохрватски',
            'si' => 'සිංහල',
            'sk' => 'slovenčina',
            'sl' => 'slovenščina',
            'sm' => 'gagana fa\'a Samoa',
            'sn' => 'chiShona',
            'so' => 'Soomaaliga; af Soomaali',
            'sq' => 'Shqip',
            'sr' => 'српски језик',
            'ss' => 'SiSwati',
            'st' => 'Sesotho',
            'su' => 'Basa Sunda',
            'sv' => 'svenska',
            'sw' => 'Kiswahili',
            'ta' => 'தமிழ்',
            'te' => 'తెలుగు',
            'tg' => 'тоҷикӣ; toğikī; تاجیکی‎',
            'th' => 'ไทย',
            'ti' => 'ትግርኛ',
            'tk' => 'Türkmen; Түркмен',
            'tl' => 'Tagalog',
            'tn' => 'Setswana',
            'to' => 'faka Tonga',
            'tr' => 'Türkçe',
            'ts' => 'Xitsonga',
            'tt' => 'татарча; tatarça; تاتارچا‎',
            'tw' => 'Twi',
            'ty' => 'Reo Mā`ohi',
            'ug' => 'Uyƣurqə; ئۇيغۇرچە‎',
            'uk' => 'Українська',
            'ur' => 'اردو',
            'uz' => 'O\'zbek; Ўзбек; أۇزبېك‎',
            've' => 'Tshivenḓa',
            'vec' => 'Vèneto',
            'vi' => 'Tiếng Việt',
            'vo' => 'Volapük',
            'wa' => 'Walon',
            'wo' => 'Wollof',
            'xh' => 'isiXhosa',
            'yi' => 'ייִדיש',
            'yo' => 'Yorùbá',
            'za' => 'Saɯ cueŋƅ; Saw cuengh',
            'zh' => '中文',
            'zh-yue' => '粵語 ',
            'zu' => 'isiZulu'
        ];
    }

    public function getSQLType(string $database = '', array $options = []): string
    {
        return 'VARCHAR(10)';
    }

    public function getLaravelSQLType(string $name, array $options = []): string
    {
        return "string($name, 10)";
    }

    public function getDocumentation(): string
    {
        return "Languages. Names are in the actual language. This follows wikipedia, prefer 'languageiso2' for an ISO standard.";
    }
}
