<?php declare(strict_types=1);

namespace Formularium;

use Formularium\Exception\Exception;

/**
 * Abstract base class for frameworks. Each framework should have a class inheriting
 * from this class.
 */
final class Formularium
{
    private static $validatorDirectories = [
        __DIR__ . '/Validator/'
    ];

    private static $datatypeDirectories = [
        __DIR__ . '/Datatype/'
    ];

    private function __construct()
    {
        // empty
    }

    public static function appendDatatypeDirectory($dir)
    {
        self::$datatypeDirectories[] = $dir;
    }

    public static function appendValidatorDirectory($dir)
    {
        self::$validatorDirectories[] = $dir;
    }

    /**
     * Returns a list of datatype class names
     *
     * @return array
     */
    public static function getDatatypeNames(): array
    {
        foreach (self::$validatorDirectories as $dir) {
            $files = scandir($dir);
            if (!$files) {
                throw new Exception('Datatypes not found');
            }
            $datatypes = array_map(
                function ($x) {
                    return str_replace('Datatype_', '', str_replace('.php', '', $x));
                },
                array_diff($files, array('.', '..'))
            );
    
            // TODO: avoid abstract classes dinamically
            $datatypes = array_filter(
                $datatypes,
                function ($t) {
                    return ($t !== 'number' && $t !== 'choice' && $t !== 'association' && $t !== 'country');
                }
            );
        }

        return $datatypes;
    }

    /**
     * Returns a list of datatype class names
     *
     * @return array
     */
    public static function getValidatorNames(): array
    {
        foreach (self::$validatorDirectories as $dir) {
            $files = scandir($dir);
            if (!$files) {
                throw new Exception('Validators not found');
            }
            $validators = array_map(
                function ($x) {
                    return str_replace('.php', '', $x);
                },
                array_diff($files, array('.', '..'))
            );
        }
        return $validators;
    }

    public static function scalarGraphqlDirectives(): string
    {
        $classes = static::getDatatypeNames();
        $graphql = [];
        foreach ($classes as $name) {
            $v = Datatype::factory($name);
            $className = get_class($v);
            $graphql[] = "scalar $name @scalar(class: \"{$className}\")";
        }

        return '
# File generated by Formularium.
# Do not edit this file directly.

' . join("\n\n", $graphql);
    }

    public static function validatorGraphqlDirectives(): string
    {
        $classes = static::getValidatorNames();
        $graphql = [];
        foreach ($classes as $name) {
            $graphql[] = Validator::class($name)::getMetadata()->toGraphql();
        }

        return '
# File generated by Formularium.
# Do not edit this file directly.

' . join("\n", $graphql);
    }
}
