<?php declare(strict_types=1);

namespace Formularium;

use Formularium\Exception\Exception;

/**
 * Abstract base class for frameworks. Each framework should have a class inheriting
 * from this class.
 */
class Formularium
{
    /**
     * Returns a list of datatype class names
     *
     * @return array
     */
    public static function getDatatypeNames(): array
    {
        $files = scandir(__DIR__ . '/Datatype/');
        if (!$files) {
            throw new Exception('Datatypes not found');
        }
        $datatypes = array_map(
            function ($x) {
                return str_replace('Datatype_', '', str_replace('.php', '', $x));
            },
            array_diff($files, array('.', '..'))
        );
    
        // TODO: avoid abstract classes
        $datatypes = array_filter(
            $datatypes,
            function ($t) {
                return ($t !== 'number' && $t !== 'choice' && $t !== 'association');
            }
        );

        return $datatypes;
    }

    /**
     * Returns a list of datatype class names
     *
     * @return array
     */
    public static function getValidatorNames(): array
    {
        $files = scandir(__DIR__ . '/Validator/');
        if (!$files) {
            throw new Exception('Validators not found');
        }
        $validators = array_map(
            function ($x) {
                return str_replace('.php', '', $x);
            },
            array_diff($files, array('.', '..'))
        );
    
        return $validators;
    }

    public static function getDatatypeValidators(): array
    {
        $datatypes = self::getDatatypeNames();

        $validators = [];

        foreach ($datatypes as $name) {
            $datatype = Datatype::factory($name);
            $validators = array_merge($validators, $datatype->getValidatorMetadata());
        }

        $classes = static::getValidatorNames();
        foreach ($classes as $name) {
            $v = Validator::factory($name);
            $graphql[] = $v->getMetadata()->toGraphql();
        }
        
        return $validators;
    }

    public static function validatorGraphqlDirectives(): string
    {
        $classes = static::getValidatorNames();
        $graphql = [];
        foreach ($classes as $name) {
            $v = Validator::factory($name);
            $graphql[] = $v->getMetadata()->toGraphql();
        }

        return '
# File generated by Formularium.
# Do not edit this file directly.

' . join("\n", $graphql);
    }

    public static function scalarGraphqlDirectives(): string
    {
        $classes = static::getDatatypeNames();
        $graphql = [];
        foreach ($classes as $name) {
            $v = Datatype::factory($name);
            $className = get_class($v);
            $graphql[] = "scalar $name @scalar(class: \"{$className}\")";
        }

        return '
# File generated by Formularium.
# Do not edit this file directly.

' . join("\n\n", $graphql);
    }



    public static function graphqlDirectives(): string
    {
        // TODO: review with ValidatorMetadata;
        $validators = static::getDatatypeValidators();
        $graphql = [];

        foreach ($validators as $name => $v) {
            $args = array_map(
                function ($a) {
                    return <<<EOF
    """
    {$a['comment']}
    """
    {$a['name']}: {$a['type']}

EOF;
                },
                $v['args']
            );

            $argString = '';
            if ($args) {
                $argString = "(\n" . join("\n", $args) . ')';
            }
            $graphql[$name] = <<< EOF
"""
{$v['comment']}
"""
directive @{$name}{$argString} on FIELD_DEFINITION

EOF;
        }

        unset($graphql['required']); // ! already does this

        return '
# File generated by Formularium.
# Do not edit this file directly.

' . join("\n", $graphql);
    }
}
