include: 
  - coverage-report/
  - coverage-report/.css/
  - coverage-report/.icons/
  - coverage-report/.js/

keep_files:
  - coverage-report/
  - coverage-report/.css/
  - coverage-report/.icons/
  - coverage-report/.js/

